DFE-Digital/manage-teacher-training-applications-prototype

app/assets/sass/components/_tag.scss, app/filters.js, app/routes/application.js, app/views/application/change-status.njk, app/views/application/index.njk, app/views/application/make-offer.njk, app/views/index.njk
This branch is currently driving the Heroku app for research:
https://manage-applications-beta.herokuapp.com/
- Rename existing statuses
- Introduce new child-statuses
- Make actions on "change status" active
- Add screen for making an offer
- In review and recruited didn't make sense to users
- It wasn't clear where interviewing and offers made would sit
- Top level statuses are ones that the provider can put a candidate into:
- New
- Interviewing (previously In review)
- Offer made
- Confirmed (previously recruited)
- Rejected
- Sub-status represent the variety of states within those top levels, eg rejected for different reasons, or types of offer and whether conditions are met or unmet.
This is a quick design to get the statuses in, there's no reason the nice panel boxes can't come …
=> New statuses and making an offer

app/views/application/index.njk
Updated status info, no longer showing DBD:
=> Remove DBD, update status info

app/routes.js, app/routes/email.js, app/views/application/index.njk, app/views/email/candidate-accepted-offer.njk, app/views/email/candidate-declined-offer.njk
- Email sent when candidate declines an offer
- Email sent when candidate accepts an offer.
Links to these emails are hidden in the UI. For an accepted or declined application, click on the status badge to see the respective message.
=> Initial email content

app/data/applications.js, app/data/session-data-defaults.js, app/views/_includes/application/personal-statement.njk
Adds ‘Getting support to become a teacher’ question to view of application form that providers see:
At this stage, this is more about surfacing this answer in the provider interface. We need to carry out research about how best to present this information to providers.
See [corresponding PR for candidate application question](https://github.com/DFE-Digital/apply-for-postgraduate-teacher-training-prototype/pull/301).
=> Add getting support answer to provider interface

app/views/_includes/application/personal-statement.njk
- Label suitability as "safeguarding" for providers, as it's a term they know and understand.
- Put the details at the bottom because:
- most users won't complete these details
- we don't want providers to reject candidates who do disclose something out of hand
Goes with https://github.com/DFE-Digital/apply-for-postgraduate-teacher-training-prototype/pull/323
=> Include suitability to work with children in provider view

app/assets/sass/components/_table.scss, app/views/index.njk
The little arrows on the sortable table buttons were positioned absolutely outside the bounds of the statically positioned buttons.
When within a scrollable area (like with the filters) this causes a horizontal scroll bar.
This addresses this.
=> Fix overflow issue for sortable tables

app/views/application/confirm-conditions-met.njk, app/views/application/confirm-conditions-not-met.njk
Before:
After:
Same for other path.
=> Show conditions on confirmation screens for marking as met/not met

app/routes/application.js, app/routes/make-different-offer.js, app/routes/make-offer.js, app/views/application/decision.njk, app/views/application/different-course--conditions.njk, app/views/application/different-course--confirm.njk, app/views/application/different-course--provider.njk
Better UX to edit course, location, provider
Hi @adamsilver 
I tweaked the order again because although location seems less important than course we show them as course, location and provider and I feel we should be consistent. From candidate POV where they train probably just as important as what.
Have done some words – this bit should be body copy:
**(you'll be able to add conditions and recommendations)**
Then further into the journey it should be something like (have done this for training provider but not others:
Change training provider
Current candidate choices
Select alternative provider
Change course
Current candidate choices
Select alternative course
Change location
Current candidate choices
Select alternative location
At this point, we shouldn't present the current training …
=> Content change course, location, provider

app/routes/application.js, app/views/application/index.njk
No need to use name as this is h1.
'Candidate enrolled' can mean both 'Candidate enrolled themselves' and 'Candidate was enrolled' – I think it's fine as is
=> Content panel headings update

app/views/_includes/offer-summary.njk, app/views/offer/change-course/confirm.njk, app/views/offer/change-course/course.njk, app/views/offer/change-course/location.njk, app/views/offer/change-location/confirm.njk, app/views/offer/change-location/location.njk, app/views/offer/change-provider/confirm.njk, app/views/offer/change-provider/course.njk, app/views/offer/change-provider/location.njk, app/views/offer/change-provider/provider.njk
- Deduped candidate name on check screens
- Add standard change links on check answers page
- Match content where possible with make offer flows
=> Make ‘change offer’ flows consistent with ‘Make offer’ flows

app/routes/users.js, app/views/onboard/index.njk, app/views/onboard/step2.njk, app/views/onboard/step3.njk, app/views/users/index.njk, app/views/users/new-check.njk, app/views/users/new.njk
- Add flow for onboarding (setting up relationships between organisations)
- Update add user flow to reflect new organisation relationships
- This is a very first stab just to get some feedback from users
- Content needs work for sure
- The check answers screen for adding users isn't clear enough. In this example especially, it just duplicates what's in the summary list above. If we can iterate this in the morning, fab.
cc @billwessel-dfe @laurahermionetennant92
=> Adam titan permissions

app/data/applications.js, app/routes/application-list.js, app/views/_includes/application-card.njk, app/views/_includes/filter-panel.njk, app/views/application/index.njk, app/views/index.njk, package.json
Rules for how the filter will work:
The locations filter will only appear if there are multiple locations
If there are multiple locations, then the location filter will only show once the user has selected a provider filter. For example, the user will only see locations for Growing Expert Teachers once they select Growing Expert Teachers.
If a user removes an organisation then any selected location filters for that organisation will be automatically removed.
For (2) we know there is a risk that a user with low-digital literacy/a first time user may not spot the appearance of the additional filter, but we will solve this when we look at onboarding users generally.
The reason for this is because:
1. we have extremely limited space to work in so we can’t simply nest the location checkboxes …
=> Add location name to card and details and add filter

app/views/onboard/check.njk, app/views/onboard/step1-part2.njk, app/views/onboard/step1.njk, app/views/organisations/show.njk
Screenshots: https://trello.com/c/VFw3VKTj/2112-design-dont-ask-users-to-setup-permissions-for-an-organisation-that-ratifies-and-runs-their-own-courses
=> Remove the need to set up permissions for courses you run AND ratify

app/views/application/index.njk
Candidate facing content added.
Think we might need to do something with a subhead – maybe 
Candidate response
to distinguish their response from guidance when the details component is open
=> Content provider context

app/views/_includes/application/diversity-information.njk, app/views/application/index.njk
Make details text more explicit that it's the guidance given to candidates.
=> Make details text clearer

app/views/_components/icon/template.njk, app/views/_includes/application/school-experience.njk, app/views/_includes/application/work-history.njk, app/views/_includes/permissions-guidance.njk, app/views/account/notifications/index.njk, app/views/account/organisational-permissions/show.njk, app/views/account/profile.njk, app/views/account/users/change-organisations/check.njk, app/views/account/users/change-organisations/permissions1.njk, app/views/account/users/change-permissions.njk, app/views/account/users/new/check.njk, app/views/account/users/new/permissions.njk, app/views/account/users/show.njk, app/views/interviews/index.njk, app/views/onboard-notifications/check.njk, app/views/onboard/check.njk
* Adds `alert` and `info` icon types to `appIcon` component
* Replaces tick icon on interviews page with alert icon
* Renames `tick` to `check` to match name used on production
* Alert icon is wider, meaning icon SVG viewport needs to be wider… nice side effect of this meaning we don’t need to add a right margin (potentially controversial change)
=> Add alert and info icons

app/assets/sass/application.scss, app/data/generators/disability.js, app/data/generators/interview-needs.js, app/data/generators/safeguarding.js, app/data/generators/work-history.js, app/views/_components/no-information-shared/macro.njk, app/views/_components/no-information-shared/template.njk, app/views/_includes/application/details.njk, app/views/_includes/application/diversity-information.njk, app/views/_includes/application/english-language-qualification.njk, app/views/_includes/application/no-information-shared.njk, app/views/_includes/application/school-experience.njk, app/views/_layout.njk, app/views/application/index.njk, app/views/application/interviews/edit/index.njk, app/views/application/interviews/index.njk, app/views/application/interviews/new/index.njk, app/views/application/notes/index.njk, app/views/interviews/index.njk, app/views/interviews/past.njk, scripts/generate-applications.js
We've made a series of changes to the disability, interview needs and safeguarding sections. The aim was to bring the sections more in line with the rest of the page and make the content clearer, such as by giving the exact questions asked and the exact responses (including generic ones from the radio button text).
We've also removed details components which revealed guidance, as we plan to move this into the guidance section. We don't think that users need to be able to access it within every candidate's application.
=> 3088 distinguish not asked questions from not answered

app/routes/reconfirm-offer.js
See https://trello.com/c/SYj9Jfto/3053-bug-in-proto-reconfirming-an-offer-disappears-from-the-list-eg-eloise-wells
=> Fix offer reconfirmation

app/views/_layout.njk
Fixes the issue where a user selects "Applications" from the main menu, after previously carrying out a search, and the search doesn't clear as expected.
https://trello.com/c/r0UtnmEr/3424-applications-list-clear-the-search-when-a-user-selects-applications-from-the-menu
=> Clear application search

app/views/_includes/permissions-checkboxes.njk, app/views/account/organisational-permissions/show.njk, app/views/account/profile.njk, app/views/account/users/change-organisations/check.njk, app/views/account/users/change-organisations/permissions1.njk, app/views/account/users/change-permissions.njk, app/views/account/users/new/check.njk, app/views/account/users/new/index.njk, app/views/account/users/new/permissions.njk, app/views/account/users/show.njk, app/views/onboard/check.njk, app/views/onboard/index.njk
I've updated the 'Make decisions' permission to 'Make decisions and set up interviews' throughout.
I also fixed a typo in app/views/_includes/permissions-checkboxes.njk, which isn't in production.
=> Added 'set up interviews' to make decisions permission

app/views/_layout-register.njk
Remove unnecessary macros from the `_layout-register.njk` file.
=> Fix missing macro errors

app/routes/data.js, app/views/_layout.njk, app/views/data/export/hesa.njk, app/views/data/export/index.njk, app/views/data/index.njk, app/views/data/statistics/conversion.njk, app/views/data/statistics/progress.njk, app/views/data/statistics/status.njk
Included in this change:
- Change "Statistics and data" to "Reports and export data" in the routes, menu, breadcrumbs and page title
- Add spacing between list items
- Move alternative progress of applications report link to the footer
=> Update reports and export data content

app/data/generators/assigned-users.js
Fix: `faker.random.number` is now located in `faker.datatype.number`
=> Fix faker deprecation warnings

start.js
The check creates an error on Heroku:
```
Latest build failed
Could not create review app. Postdeploy execution timed out.
```
We don't need the check, even though it's nice for the GOV.UK Design System team to know prototype kit usage.
=> Remove usage data check

app/routes/activity-log.js
The activity log shows events in the future. This simple fix filters out all future events, so that the activity log only shows historical items.
This is an interim fix whilst we work on correcting the event data.
=> Only show activity from today and older

app/routes/data.js, app/views/data/index.njk
The links to the general and HESA exports included the organisation ID, but that isn't necessary as those exports are cross-organisation. I removed the organisation ID and amended the routing accordingly.
=> Fixed routing for data exports

app/routes/interviews.js
When setting up an interview, the application status doesn't change from `Received` to `Interviewing`. This PR resolves the issue.
In addition, when an interview is cancelled, the application status is changed from `Interviewing` to `Received`.
=> Fix status change from received to interviewing

package.json
There are a number of deprecation warnings related to dependencies such as `govuk-frontend` and caused by using the latest version of Sass. For example:
```
DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.
```
Rollback Sass version from `1.35.2` to `1.32.13` and wait until `govuk-frontend` updates their Sass.
Use the tilde `~` to only patch the version.
=> Rollback Sass version to fix deprecation warnings

app/data/helpers/statistics.js
Compare dates to 31 August of the current year. This date is derived from the cut-off point for school/college cohorts.
=> Fix age comparison

app/views/_includes/applications/degrees.njk, app/views/_includes/applications/gcses.njk, app/views/_includes/applications/other-qualifications.njk, scripts/generate-applications.js
Changes made:
- Rename "Country" to "Country and territory" in degree, GCSE and other qualifications
- Add "Have you completed this degree?" to the degree section and display if the answer is no
- Split the "comparability" line in the degree and GCSE sections into separate lines, one for "UK ENIC reference number" and  another for "Comparable UK qualification"
- Handle missing ENIC number in the degree and GCSE sections: display "Do you have a UK ENIC statement of comparability?" if the answer is no.
=> Fix missing or incomplete sections in qualifications

app/data/generators/events.js, app/data/generators/offer.js, app/filters.js, app/routes.js, app/routes/edit-course.js, app/routes/edit-offer.js, app/routes/examples.js, app/routes/make-offer.js, app/views/_components/event-application/template.njk, app/views/_components/event-offer/template.njk, app/views/_components/offer-panel/template.njk, app/views/_examples/courses/index.njk, app/views/_examples/index.njk, app/views/_examples/qualifications/degree.njk, app/views/_examples/qualifications/english.njk, app/views/_examples/qualifications/gcse.njk, app/views/_examples/qualifications/index.njk, app/views/_includes/applications/course-details.njk, app/views/applications/course/check.njk, app/views/applications/decision.njk, app/views/applications/offer/edit/check.njk, app/views/applications/offer/new/check.njk, app/views/applications/offer/show.njk, scripts/generate-applications.js
- fix bug with location not showing in the summary list when editing a course
- added qualifications data to the applications generators
- added qualifications to summary lists
- change course
- make offer
- edit offer
- added qualifications and funding type to application log and timeline
- added an `arrayToList` filter
- added a `courses` example page so we can see all course detail in the prototype
=> Fixes to change course

package.json
We don't have any tests, so these are redundant.
=> Remove test dependencies

package.json
We don't run this ever, and our current code doesn't follow the linting rules from `standard`.
=> Remove linting

.gitignore, .npmrc, package-lock.json
This means that all instances (local development and deploys on heroku) will use the same versions of all dependencies, which should help avoid errors caused by different versions being used.
=> Add package lock

app/data/helpers/application.js
The status was being set as "conditions met" even if one of the conditions was "not met" due to a bug with the logic, which only checked whether there were no conditions still pending.
=> Bugfix: setting conditions not met

app/views/guidance/_content/dates-and-deadlines.md
Providers sometimes want to know the dates and deadlines for the next recruitment cycle, particularly towards the end of a cycle. We added a table showing to show this information.
=> Add next cycle’s dates and deadlines to the service guidance

app/views/applications/offer/new/conditions.njk
A bit of a placeholder to explain to providers that candidates will be asked to request 2 references if they accept an offer, and to prompt providers to add further conditions if they need to say anything specific about references...
A future enhancement could be to add an optional text box directly within the 'References' sub-section, to avoid the awkward reference to the interface below...
=> Add references guidance to 'Make offer' flow

app/data/generators/references.js, app/views/_includes/applications/references.njk, app/views/_includes/applications/sub-nav.njk, app/views/applications/references/index.njk, scripts/generate-applications.js
We've updated the design to make things a bit clearer.
Changes:
* Moves the references into "summary cards", which gives them a border and a title
* 'Type' row removed, as this is now in the card title
* "How the candidate knows them and how long for" row combines both what the candidate said and what the referee says (if they say it's not correct) or just says it's confirmed.
* "Concerns about the candidate working with children" label updated slightly, and shows either "No concerns" or the concerns given by the referee
* "Reference" contains the actual reference. For carried over references from the past cycle this would say "Does the candidate have the potential to teach?"
* Where the candidate hasn't accepted an offer yet, adds a line of guidance
* Where a candidate has accepted an …
=> References tab changes

app/views/applications/offer/new/conditions.njk
The conditions of offer page had an early version of the new references content. I've changed it to match production.
=> Changed content to match production

app/views/_components/offer-panel/template.njk
One participant was nervous that, because we didn't mention the subject in the SKE course condition summary, this wouldn't get specified to trainees and so they might go off and try and do a SKE course in a different subject.
Adding this row (uneditable) may help to reassure them that the subject will be specified.
=> Add course subject to SKE course condition summary

app/views/applications/offer/new/ske-reason.njk
Made the hint text about the candidate receiving a bursary clearer to say that its a SKE bursary rather than confusion over ITT or SKE bursary.
=> Make hint text about SKE bursary clearer

app/filters.js, app/routes/make-offer.js, app/views/_components/offer-panel/template.njk, app/views/applications/offer/new/check.njk, app/views/applications/offer/new/ske-length.njk, app/views/applications/offer/new/ske-reason.njk, app/views/applications/offer/new/ske.njk, app/views/applications/offer/show.njk, scripts/generate-applications.js
The previous iteration focused on Maths courses only, and made the assumption that only a maths SKE course could be required. We think this holds true for maths, but for other courses it’s not quite so simple...
For language courses, providers can require 2 different SKE courses in 2 different languages.  In theory we could possibly infer which 2 languages from the language subjects attached to the course in Find, but in practice a fair number of courses on Find just have "Modern languages" as the subject, so we might need to ask...
➡️ [Preview](https://manage-itt-pr-616.herokuapp.com/start)
There only seem to be SKE courses for 3 modern languages, plus "Ancient languages", assuming the [course directory](https://www.gov.uk/government/publications/subject-knowledge-enhancement-course-direc …
=> SKE course requirements: languages and PE with Ebacc

app/views/applications/offer/new/ske-reason.njk
There doesn’t _seem_ to be any overlap between these 2 options? 
We had thought that it might be possibly for someone to have a degree which doesn't match the subject AND it was from more than 5 years ago, so both options applied.
But perhaps we can simplify things by switching these to radios and updating the wording to make these options more mutually-exclusive?
=> Change SKE course reasons from checkboxes to radios

app/assets/sass/application.scss, app/filters.js, app/routes/applications.js, app/routes/reject-application.js, app/views/_includes/applications/gcses.njk, app/views/_includes/candidate-feedback.njk, app/views/_includes/reasons/personal-statement.njk, app/views/_includes/reasons/qualifications.njk, app/views/applications/reject/check.njk, app/views/applications/reject/degree.njk, app/views/applications/reject/english.njk, app/views/applications/reject/maths.njk, app/views/applications/reject/other-reasons.njk, app/views/applications/reject/other.njk, app/views/applications/reject/reasons.njk, app/views/applications/reject/recommend.njk, app/views/applications/reject/science.njk, scripts/generate-applications.js
This is a sketch of how we might pull out the ITT criteria from the existing "reject" flow by asking about each criteria on a separate page. We’d skip these questions where it was obvious the candidate met the criteria (eg a UK bachelors degree, or a C at GCSE) and would only show the relevant pages where it was less clear cut.
The aim here would be to give providers better guidance on the ITT criteria, and a prompt to get in touch if they are unsure whether a candidate meets the criteria.
This is an alternative to #637 which lists them all on the same page.
=> Update reject flow with a page per ITT criteria

app/views/_components/conditions-panel/template.njk, app/views/changes-to-this-service/index.njk, app/views/feedback/index.njk, app/views/guidance/show.njk, app/views/privacy/show.njk
Replace `markdownToHtml` with `govukMarkdown` from [string filters](https://x-govuk.github.io/govuk-prototype-filters/string/).
(Thanks @paulrobertlloyd!)
=> Bugfix: markdown filter

app/filters.js
This was accidentally dropped when updating the kit, and is used on the rejection feedback page.
=> Bugfix: add missing 'includes' filter

app/routes/interviews.js, app/routes/make-offer.js
Some of the content, eg for buttons and headings, seems to be stored in a separate [`content.js`](https://github.com/DFE-Digital/manage-teacher-training-applications-prototype/blob/main/app/data/content.js) file.
For some reason the upgrade to v13 of the kit meant this variable was no longer being made available to the page templates.
The simplest fix was to list it within the `res.render()` calls of each of the pages in the routes file.
Longer term it might make sense to move away from this file and just copy all of the content back into the individual templates?
=> Bugfix: expose content to pages

app/views/applications/offer/new/check.njk
There's no `push` filter declared, but we don't need it as we can use the native `.push()` function (albeit a bit clunky).
=> Bugfix: use native push function

app/views/_includes/applications/interview-needs.njk
As part of continuous applications, we updated the 'Interview needs' question on Apply. This means we need to match that new content on Manage:
=> Updated interview needs content

README.md, app/assets/sass/application.scss, app/assets/sass/core/_filter-layout.scss, app/assets/sass/core/_tag.scss, app/data/helpers/cycles.js, app/filters.js, app/routes/application-list.js, app/routes/applications.js, app/routes/reports.js, app/views/_includes/application-card.njk, app/views/_includes/applications/h1.njk, app/views/_includes/applications/respond-prompt.njk, app/views/_includes/filter-panel.njk, app/views/_layout.njk, app/views/applications/index.njk, app/views/applications/notes/index.njk, app/views/applications/notes/new.njk, app/views/applications/offer/withdraw/check.njk, app/views/applications/show.njk, app/views/reports/applications/index.njk, scripts/generate-applications.js
Currently, when a provider receives an application, it stays in the ‘received’ status until a decision is made.
This might be a brand new application that nobody has looked at, one that is being reviewed offline, or one that has been shortlisted for an interview/offer.
This makes it hard for providers to tell which applications need their attention.
The change proposes more granular statuses to help providers manage their workload. and a new way of presenting/navigating applications.
* Replace 'received' with more granular statuses
* New
* In review
* Shortlisted 
* Grouping of the new and proposed statuses into categories
* Received
* In progress
* Complete
* Tabs to navigate between categories
* Pseudo-tabs/data blocks used to show the more granular statuses within
* New actions to …
=> More granular Received statuses and new navigation

app/filters.js, app/routes/withdraw-application.js, app/views/_components/offer-panel/template.njk, app/views/_includes/application-card.njk, app/views/applications/offer/withdraw/check.njk, app/views/applications/offer/withdraw/index.njk, app/views/applications/show.njk, app/views/applications/withdraw/index.njk, package-lock.json, package.json
[Trello card](https://trello.com/c/9EBsw6zd/524-design-an-alternative-to-withdraw-on-candidates-behalf)
Allowing providers to end an application post-offer, and allowing to candidates to confirm when a provider submits a 'withdraw on candidate's behalf' request.
=> Withdrawal updates
