app/data/session-data-defaults.js
app/views/_layout.njk
app/views/application/index.njk

By setting environment variable of `BARE=true`, UI elements are removed.

Enable bare application view

---

app/data/applications.js
app/views/_includes/application/degrees.njk
app/views/_includes/application/gcses.njk
app/views/_includes/application/language-skills.njk
app/views/_includes/application/other-qualifications.njk
app/views/_includes/application/personal-statement.njk
app/views/_layout.njk
app/views/application/decision.njk
app/views/application/index.njk
app/views/application/reject.njk

Provider UI tweaks

---

app/views/application/confirm.njk
app/views/application/offer.njk

Provider UI content changes

---

app/assets/sass/components/_banner.scss

Now uses same padding and margin values.

Align banner styles with error summary component

---

app/views/_components/banner/template.njk
app/views/_content-wide.njk
app/views/_content.njk
app/views/_form-wide.njk
app/views/_form.njk
app/views/application/index.njk

Update banner placement

---

app/views/_includes/application/personal-statement.njk
app/views/_includes/application/reasonable-adjustments.njk
app/views/application/index.njk

- Remove ‘any other information’ from showing in application
- Move and reword ‘training with a disability/reasonable adjustments’ question to be consistent with candidate prototype.

Update application to reflect training with a disability questions

---

app/data/applications.js
app/filters.js
app/routes/application.js
app/views/application/confirm-withdraw.njk
app/views/index.njk

- fixed status filter
- added flow for withdrawing (rejecting after offering) an offer

Withdrawing an offer flow

---

app/assets/sass/components/_tag.scss
app/data/applications.js
app/filters.js
app/routes/application.js
app/routes/users.js
app/views/index.njk

Added **withdrawn by us** and **withdrawn by candidate** statuses

Withdrawn statuses and flash message for users

---

app/assets/sass/components/_tag.scss
app/data/applications.js
app/filters.js
app/routes.js
app/routes/application.js
app/routes/conditions.js
app/views/application/confirm-conditions-met.njk
app/views/application/confirm-conditions-not-met.njk
app/views/application/index.njk
app/views/application/mark-conditions.njk

Needs an end-to-end content crit @laurahermionetennant92 
Note that I've already incorporated @emmajhf's suggestions on the CTA button text and h1 on the subsequent page.

Conditions met and not met flow

---

app/views/application/index.njk

- Sort out grey panel with correct meta data depending on status
- add course details panel on details view

Details view course info

---

app/data/application-utils.js
app/data/applications.js
app/routes/application.js
app/routes/conditions.js
app/views/application/index.njk

Created getConditions(application) function to use across multiple
routes.
Fixed details view display logic to check for conditions object
instead of status.offered.conditions.
Normalised stub data so that standard and non standard conditions
are consistently defined across different applications.

Make sure conditions are displayed if applicable

---

app/views/application/index.njk

Changed the heading size from Large to Medium.
Aligned everything the same with a two-third grid column.
Before
After

Fix course details heading hierarchy on details view

---

app/data/applications.js
app/views/_includes/application/reference.njk

Added 4 realistic references to the data.
Simplifed the display of a reference by removing score cards and
works with children flag.
Made sure line breaks are converted to `<br>` tags.

Add 2 realistic references for Kelly Jane Spears and Elise Briggs

---

app/views/application/confirm-withdraw.njk

Update confirmation pattern for withdraw

---

app/views/application/confirm-conditions-met.njk

Update copy for confirming conditions met

---

app/views/application/confirm-conditions-not-met.njk

Update copy for confirming conditions haven’t been met

---

app/filters.js
app/views/index.njk

Was ‘Withdrawn by candidate/us’

Update status text for withdrawn

---

app/data/session-data-defaults.js
app/views/_includes/application/personal-statement.njk
app/views/application/index.njk

Display of interview and a11y needs and safeguarding

---

app/assets/sass/components/_tag.scss
app/filters.js
app/routes/application.js
app/views/application/confirm-enrollment.njk
app/views/application/index.njk

Flow:
https://www.loom.com/share/769773d6622a44bea50cd71a73cb2d37

Finish enrollment flow

---

app/routes/application.js
app/views/application/different-course--conditions.njk
app/views/application/different-course--confirm.njk
app/views/application/different-course--course.njk
app/views/application/different-course--location.njk
app/views/application/different-course--provider.njk
app/views/application/different-course.njk
app/views/application/edit-response.njk

Demo:
https://www.loom.com/share/533979e5da01439fb99383320565f4bb

Different offer

---

app/data/applications.js
app/filters.js
app/routes/application.js
app/views/application/index.njk
app/views/index.njk

The architecture/code for dealing with application/offer statuses was hard to follow and prone to error. 
This is my attempt at simplifying it. 
The fixing of the architecture has also meant I've fixed a few UX things along the way by ‘accident’ :)

Status architecture

---

app/views/application/different-course.njk
app/views/application/edit-response.njk
app/views/application/index.njk

Hi there, few queries on this one as per Slack
Hi @Adam @James Asamoah
Actions you can take when editing your response to a candidate:
change course
keep same course but change conditions and recommendations
change location
change start date (??)
Excluded: change training provider
Also: they will want the opportunity to explain this change to the candidate. Free text field to accommodate this?
So content here could be (RB stands for radio button!):
What would you like to do?
You’ll be able to explain your decision to the candidate.
RB: Offer this candidate a different location
RB: Change your conditions or recommendations
RB: Offer this candidate a different course
hint:You can include new conditions or recommendations
RB: Change this candidate’s start date
RB: Withdraw your offer

Content change course

---

app/views/application/confirm-enrollment.njk

Hi there this needs your help – link not working (soz don't know why)
Content needs to sit below header – again, need your help to fix!

Content enrolment

---

app/assets/sass/application.scss
app/assets/sass/components/_card.scss
app/data/applications.js
app/filters.js
app/routes/conditions.js
app/views/application/index.njk

@fofr and I paired to design this:
https://www.loom.com/share/f28c35c470b04eca80d56ad499b026fe
Still a WIP but good enough to share.

New way to present and amend the various states of an application

---

app/routes/application.js
app/routes/make-different-offer.js
app/views/application/decision.njk
app/views/application/index.njk

Now conditions are saved and different offer details are saved.
Added recommendations area as well.

Different course flow fix

---

app/data/applications.js
app/routes/application.js
app/views/application/index.njk

Conditions status and not met state handled

---

app/views/application/index.njk

Offer panel headings

---

app/views/_includes/application/reference.njk

Related candidate PR: https://github.com/DFE-Digital/apply-for-postgraduate-teacher-training-prototype/pull/352

Reinstate reference types

---

app/views/application/different-course--provider.njk

Content head for offer different provider

Content head for offer different provider

---

app/routes/application-list.js
app/views/_includes/filter-panel.njk
app/views/index.njk

https://www.loom.com/share/36ccac584fec446a9667b6fef1b3c453

Let users filter the application list by typing (part of) a candidate's name

---

app/data/applications.js
app/views/_includes/application/personal-statement.njk
app/views/_includes/application/reference.njk
app/views/application/index.njk

Confirmed:
Amended:
No corcerns:
Unknown concerns:
Some concerns:

Referee relationship and safeguarding

---

app/views/_includes/application/reference.njk

Two questions for referee safeguarding question

---

app/routes/application.js
app/views/offer/change-condition-status/confirm-met.njk
app/views/offer/change-condition-status/confirm-not-met.njk
app/views/offer/change-condition-status/status.njk

https://www.loom.com/share/754bc6c60da246d0865713f97cdc013d

Change condition status

---

app/assets/sass/application.scss
app/views/_includes/application/school-experience.njk
app/views/_includes/application/work-history.njk
app/views/application/index.njk

Change style of work history entries

---

app/assets/sass/application.scss
app/data/applications.js
app/views/_includes/application-list-item.njk
app/views/_includes/application-list-item2.njk
app/views/_includes/application-list-item3.njk
app/views/_includes/application-list-item4.njk
app/views/_includes/application-list-item5.njk
app/views/index.njk

Before:
After:
Note: this is filthy code just for a testing in the next 2-3 weeks of research.

Card layout

---

app/views/application/index.njk

Before:
After:
cc @laurahermionetennant92

Personal statement just as prose content

---

app/views/application/index.njk

Content safeguarding disability labels

---

app/assets/sass/application.scss
app/data/applications.js
app/filters.js
app/routes/application-list.js
app/views/_includes/application-list-item5.njk
app/views/_includes/application/status-panel.njk
app/views/_includes/filter-panel.njk
app/views/application/index.njk
app/views/users/index.njk
app/views/users/new.njk

https://www.loom.com/share/466a7e87e03243cb8cca323fc3a2bf0a

Card layout, accredited body filter, notes, details page layout and manage users

---

app/views/application/confirm-rejection.njk
app/views/application/reject.njk

Reasons for rejection

---

app/views/_includes/reject-form-fields.njk
app/views/_includes/reject-playback.njk
app/views/_includes/reject-summary-list.njk

Content tweaks on withdraw/reject

Content tweaks on withdraw/reject

---

app/assets/sass/application.scss
app/views/application/index.njk

PDF download

---

app/data/application-utils.js
app/filters.js
app/routes.js
app/routes/application.js
app/routes/notes.js
app/views/application/notes/index.njk
app/views/application/notes/new.njk
package.json

- Changed link to button
- Add note screen
- Use existing card layout for note
- Flash message
Todo:
- Delete note
- Edit note screen

Add the create a note flow

---

app/data/applications.js
app/views/_includes/filter-panel.njk
app/views/application/index.njk
app/views/index.njk

Content updates for testing to match provider organisations

Bill provider customisation

---

app/data/applications.js
app/views/_includes/filter-panel.njk
app/views/application/index.njk
app/views/organisations/index.njk
app/views/organisations/show.njk
app/views/users/index.njk
app/views/users/show.njk

Changes made to reflect scenario for Millais Alliance for user research. Changes made to:
e.g.

Content changes

---

app/views/onboard/_includes/guidance.njk
app/views/onboard/step2.njk
app/views/users/new/permissions.njk
app/views/users/new/providers.njk

Content tweaks 1

---

app/data/applications.js
app/views/_includes/application-card.njk
app/views/_includes/filter-panel.njk
app/views/application/index.njk
app/views/organisations/index.njk
app/views/organisations/show3.njk
app/views/users/index.njk
app/views/users/show.njk

Updates to:
- filters
- applications
- organisations
- users

Content changes for testing with Somerset SCITT

---

app/views/organisations/index.njk
app/views/organisations/show.njk
app/views/organisations/show3.njk
app/views/organisations/show4.njk
app/views/organisations/show5.njk

Orgs added to the list on the organisations page and a sub-page created for each.
Change link removed from each sub-page for those 3 orgs

Added 3 orgs to the Organisations page

---

app/views/onboard/_includes/checkboxes.njk
app/views/onboard/_includes/guidance.njk
app/views/onboard/check.njk
app/views/onboard/step1-part2.njk
app/views/users/new/check.njk
app/views/users/new/permissions.njk
app/views/users/new/permissions2.njk
app/views/users/new/providers.njk
app/views/users/show.njk

Content permissions tweaks

---

app/views/application/notes/new.njk

Content note updated

---

app/views/onboard/check.njk
app/views/onboard/confirmation.njk
app/views/onboard/data-sharing-confirmation.njk
app/views/organisations/delete.njk
app/views/users/new/check.njk
app/views/users/new/permissions.njk
app/views/users/new/permissions2.njk
app/views/users/show.njk

More concise language for Invite user

Content permissions final sweep

---

app/views/users/change-permissions.njk
app/views/users/change-permissions2.njk
app/views/users/new/check.njk
app/views/users/new/permissions.njk
app/views/users/new/permissions2.njk
app/views/users/show.njk

Content Claudine change permissions

Content Claudine change permissions

---

app/assets/sass/components/_timeline.scss
app/data/application-utils.js
app/data/applications.js
app/routes/notes.js
app/views/_components/timeline/template.njk
app/views/application/notes/index.njk
app/views/application/notes/show.njk

Timeline now has a link to the relevant thing (note, application, offer, etc)

---

app/views/users/change-permissions.njk
app/views/users/change-permissions2.njk
app/views/users/new/check.njk
app/views/users/new/permissions.njk
app/views/users/new/permissions2.njk
app/views/users/show.njk

https://trello.com/c/OEF86s1T/2110-invite-a-user-and-edit-a-user-journey-content

Improve content for inviting/editing users

---

app/views/_includes/permissions-guidance.njk
app/views/onboard/step1-part2.njk
app/views/users/change-permissions.njk
app/views/users/change-permissions2.njk
app/views/users/new/permissions.njk
app/views/users/new/permissions2.njk

Content read changed to view

---

app/assets/sass/components/_application-card.scss
app/data/application-utils.js
app/data/applications.js
app/filters.js
app/routes/application-list.js
app/views/_includes/application-card.njk
app/views/_includes/filter-panel.njk
app/views/index.njk

Sort application list

---

app/views/onboard/check.njk
app/views/organisations/show.njk
app/views/organisations/show3.njk

@duncanjbrown @steventux @laurahermionetennant92

Add bullet for view applications permissions

---

app/data/applications.js
app/views/_includes/filter-panel.njk
app/views/organisations/index.njk
app/views/organisations/show.njk
app/views/organisations/show3.njk
app/views/users/index.njk
app/views/users/new/check.njk
app/views/users/new/permissions.njk
app/views/users/new/permissions2.njk
app/views/users/new/providers.njk
app/views/users/show.njk

Updated all the organisation names to be for fictional organisations, so that they can be used in demos

Generic Organisation names

---

app/views/_includes/reasons/honesty.njk

Content safeguarding hint text for when providers can't disclose

Content safeguarding hint text for when providers can't disclose

---

app/routes/application-list.js
app/views/notifications/index.njk
app/views/notifications/settings.njk
app/views/offer/change-provider/provider.njk
app/views/offer/new/change-provider/provider.njk
app/views/onboard/check.njk
app/views/onboard/index.njk
app/views/onboard/step1.njk
app/views/onboard/step2.njk
app/views/onboard/step3.njk
app/views/organisations/change-permissions.njk
app/views/organisations/edit.njk
app/views/organisations/index.njk
app/views/organisations/new.njk
app/views/organisations/show2.njk
app/views/organisations/show4.njk
app/views/organisations/show5.njk
app/views/profile/index.njk
app/views/users/change-permissions.njk
app/views/users/change-permissions2.njk
app/views/users/change-providers.njk
app/views/users/index.njk

No mentions of the old providers even in commented out or currently unused files

Further update to remove all mentions of previous provider names

---

app/views/_includes/permissions-checkboxes.njk
app/views/onboard/check.njk
app/views/onboard/step3.njk
app/views/organisations/show.njk
app/views/organisations/show3.njk

https://www.loom.com/share/439bc8fe5af44400bc82eaf879d3403b

Change org to org permissions to be radio buttons

---

app/data/application-utils.js
app/data/applications.js
app/data/session-data-defaults.js
app/filters.js
app/routes/application-list.js
app/routes/application.js
app/views/_includes/application/details.njk
app/views/_includes/application/status-panel.njk
app/views/_includes/application/sub-nav.njk
app/views/_includes/filter-panel.njk
app/views/application/cycle/edit.njk
app/views/application/index.njk
app/views/application/offer.njk
app/views/change-cycle.njk
app/views/index.njk
app/views/offer/change-course/course.njk
app/views/switch-cycle.njk
server.js

https://www.loom.com/share/799d4cc003e6467489289c1948f75fd1

Change cycle

---

app/views/_includes/reasons/why.njk

Max word count is 200 on final question:
Why are you rejecting this application?

Content word count on RforR

---

app/data/applications.js
app/data/session-data-defaults.js
app/routes/application.js
app/routes/reconfirm-offer.js
app/views/_includes/offer/offer.njk
app/views/application/cycle/edit/cycle.njk
app/views/application/index.njk
app/views/application/offer.njk
app/views/offer/new/change-location/location.njk
app/views/offer/reconfirm/check.njk
app/views/offer/reconfirm/conditions.njk
app/views/offer/reconfirm/unavailable-course/action.njk
app/views/offer/reconfirm/unavailable-course/check.njk
app/views/offer/reconfirm/unavailable-course/conditions.njk
app/views/offer/reconfirm/unavailable-location/action.njk
app/views/offer/reconfirm/unavailable-location/check.njk
app/views/offer/reconfirm/unavailable-location/conditions.njk
app/views/offer/reconfirm/unavailable-location/location.njk
app/views/switch-cycle.njk

Content changes on deferred offer

Content changes on deferred offer

---

app/views/application/decision.njk

Content respond to application tweak

Content respond to application tweak

---

app/views/_includes/permissions-checkboxes.njk
app/views/_includes/permissions-guidance.njk
app/views/account/index.njk
app/views/notifications/index.njk
app/views/onboard/check.njk
app/views/onboard/step1-part2.njk
app/views/organisations/show.njk
app/views/organisations/show2.njk
app/views/organisations/show3.njk
app/views/organisations/show4.njk
app/views/organisations/show5.njk
app/views/users/change-permissions.njk
app/views/users/change-permissions2.njk
app/views/users/new/check.njk
app/views/users/new/permissions.njk
app/views/users/new/permissions2.njk
app/views/users/show.njk

Flows affected:
1. Onboarding flow to set up permissions
2. Organisation pages
3. Organisation edit flows
4. Invite new user
5. User pages
6. User edit flows
Main thing to check is the content inside the blue information box during the onboarding flow

Add diversity permission

---

scripts/generate-organisations.js

Content video script tweak

---

app/data/session-data-defaults.js
app/routes/users.js
app/views/users/1/change-email-address/index.njk
app/views/users/1/change-name/index.njk
app/views/users/1/change-organisations/check.njk
app/views/users/1/change-organisations/index.njk
app/views/users/1/change-organisations/permissions1.njk
app/views/users/1/change-organisations/permissions2.njk
app/views/users/1/change-permissions/index.njk
app/views/users/1/change-permissions2/index.njk
app/views/users/1/delete.njk
app/views/users/1/index.njk
app/views/users/index.njk

https://www.loom.com/share/f4d99ac00e5f436db432ea3da6ed89b7

Update flow for changing access

---

app/views/_includes/application-card.njk

Switch cycle and days left to respond around

---

app/assets/sass/application.scss
app/assets/sass/components/_sub-navigation.scss
app/views/_components/sub-navigation/macro.njk
app/views/_components/sub-navigation/template.njk
app/views/_includes/application/details.njk
app/views/_includes/application/sub-nav.njk
app/views/_includes/profile-sub-nav.njk
app/views/_layout.njk
app/views/application/index.njk

Style tabs properly without overriding govuk-tabs

---

app/views/onboard-notifications/check.njk
app/views/onboard-notifications/confirmation.njk
app/views/onboard-notifications/index.njk
app/views/onboard-notifications/setup-1.njk
app/views/onboard-notifications/setup-2.njk

https://www.loom.com/share/b50eca97c94048b6926bfd532adc0d4b

Notification set up flow

---

app/data/generators/interviews.js
app/routes/interviews.js
app/views/application/interviews/edit/check.njk
app/views/application/interviews/edit/index.njk
app/views/application/interviews/index.njk
app/views/application/interviews/new/check.njk
app/views/application/interviews/new/index.njk
app/views/interviews/index.njk
scripts/generate-applications.js

- Better data generation
- Include location

Interviews take a location

---

app/views/_components/icon/template.njk

```nunchucks
{{ appIcon({
icon: "cross"
}) }}
```

Add cross icon

---

app/data/users.json
app/views/_includes/permissions-checkboxes.njk
app/views/_includes/permissions-guidance.njk
app/views/onboard/check.njk
app/views/onboard/relationship1.njk
app/views/organisations/edit.njk
app/views/organisations/show.njk

Clarity around view only permission and change links

Permission tweaks

---

app/assets/javascripts/modules/filter-toggle-button.js
app/assets/sass/application.scss
app/assets/sass/components/_action-bar.scss
app/assets/sass/components/_filter-layout.scss
app/assets/sass/components/_filter.scss
app/assets/sass/components/_search.scss
app/views/_components/filter/macro.njk
app/views/_components/filter/template.njk
app/views/_includes/filter-panel.njk
app/views/_layout.njk
app/views/index.njk

Click view deployment button below and play about with the filters on small and large screens.

Filters: copy across from MOJ and improve for small screens

---

app/routes/change-offer-course.js
app/routes/change-offer-location.js
app/routes/change-offer-provider.js
app/routes/offer.js

When the user changes an offer (either course details or conditions), the success message is now 'New offer sent'.

Changed content of success message after changing offer

---

app/views/_includes/reasons/actions.njk
app/views/_includes/reasons/application-quality.njk
app/views/_includes/reasons/honesty.njk
app/views/_includes/reasons/missing-qualifications.njk
app/views/_includes/reasons/safeguarding.njk

Removed `classes: "govuk-checkboxes--small"` attribute

Fix nested checkbox size

---

app/views/_includes/filter-panel.njk

See https://trello.com/c/3Whr8Jsb/3000-design-add-status-for-conditions-not-met

Add conditions not met status

---

app/data/generators/rejection.js
scripts/generate-applications.js

See https://trello.com/c/mqkOrAWA/3005-show-feedback-for-rejected-applications-generated-with-faker

Add Faker rejected reasons

---

app/data/generators/withdrawal.js
app/views/_components/offer-panel/template.njk
app/views/application/offer/index.njk

See: https://trello.com/c/6l38IW4Z/3062-show-feedback-for-withdrawn-applications-generated-with-faker

Add Faker withdraw reasons

---

app/filters.js
app/routes/activity-log.js
app/views/_components/all.scss
app/views/_components/log-card/_log-card.scss
app/views/_components/log-card/template.njk
app/views/_components/previous-next-navigation/README.md
app/views/_components/previous-next-navigation/_previous-next-navigation.scss
app/views/_components/previous-next-navigation/index.html
app/views/_components/previous-next-navigation/macro.njk
app/views/_components/previous-next-navigation/template.njk
app/views/_includes/activity-log/events-timeline.njk
app/views/_layout.njk
app/views/activity/index.njk

See https://trello.com/c/i4PkJ5G9/3061-design-activity-log-timeline

Update activity log

---

app/routes/application-list.js
app/views/_includes/application-card.njk
app/views/_includes/filter-panel.njk
app/views/index.njk

See https://trello.com/c/p8Z3QHP8/1901-design-filter-by-study-mode

Add study mode filter

---

app/data/generators/course.js

See https://trello.com/c/aDLtsmy9/3097-fix-course-code-data-in-prototype

Fix course code data

---

app/filters.js
app/filters/dates.js
app/views/_includes/activity-log/events-timeline.njk
package.json

See https://trello.com/c/vvZYaDo9/3108-prototype-favour-luxon-over-moment-for-date-functions

Remove Moment dependency

---

app/data/generators/events.js
app/data/helpers/dates.js
scripts/generate-applications.js

See https://trello.com/c/iDd7LszG/3069-fix-application-event-times-in-activity-log-generated-by-faker

Fix event times

---

app/data/session-data-defaults.js
app/routes.js
app/routes/notifications.js
app/views/_includes/filter-panel.njk
app/views/_layout.njk
app/views/account/index.njk
app/views/account/notifications/index.njk

- added a form to let users change settings
- updated content on account landing page to match settings
- add notification banner confirming the settings have been saved

Let users enable and disable email notifications about applications

---

app/routes/activity-log.js
app/routes/application-list.js
app/routes/applications.js
app/routes/interviews.js
app/views/_components/application-card/_application-card.scss
app/views/_components/search/_search.scss
app/views/_components/search/template.njk
app/views/_includes/application-card.njk
app/views/_includes/filter-panel.njk
app/views/_includes/search-panel.njk
app/views/index.njk

See: https://trello.com/c/mx9njjfc/3137-design-letting-providers-search-by-candidate-reference-number

Add search by candidate name or reference

---

app/views/index.njk

Fixes the messages displayed when a user conducts a search or applies a filter, but no results are returned.

Fix search empty state messages

---

app/views/_includes/applications/personal-details.njk

Split up candidate name

---

app/assets/sass/application.scss
app/data/generators/school-experience.js
app/data/generators/work-history.js
app/views/_includes/applications/school-experience.njk
app/views/_includes/applications/work-history.njk
app/views/applications/show.njk
scripts/generate-applications.js

- move interviews lower down
- move work history above degrees
- mark roles relevant to teaching (instead of worked with children)
- mark approximate dates
- mark gaps
- handle when no unpaid experience added
- improve generators
- move safeguarding and disability to bottom

Work history updates

---

app/views/applications/show.njk

I changed 'Safeguarding issues' to 'Criminal record and professional misconduct' in the application details.

Criminal record professional misconduct

---

app/data/generators/events.js
app/data/generators/offer.js
app/data/session-data-defaults.js
app/filters.js
app/routes/application-list.js
app/routes/offer.js
app/routes/reconfirm-offer.js
app/routes/settings.js
app/views/_includes/applications/diversity-information.njk
app/views/_includes/filter-panel.njk
app/views/_includes/reasons/conditions.njk
app/views/applications/offer/show.njk
app/views/export/index.njk
scripts/generate-applications.js

Change Accepted to Awaiting conditions and Conditions met to Ready to enroll

---

app/data/generators/contact-details.js
app/data/generators/personal-details.js
app/views/_includes/applications/application-details.njk
app/views/_includes/applications/personal-details.njk
scripts/generate-applications.js

Let users see when a candidate’s application is eligible for ‘home student tuition fees‘
See: https://trello.com/c/piifWpEd/3450-guidance-for-fee-status-on-manage

Add fee status guidance

---

app/data/helpers/application.js
app/routes/reject-application.js
app/views/_includes/candidate-feedback.njk
app/views/_includes/reasons/sponsor-visa.njk
app/views/applications/reject/index.njk

See: https://trello.com/c/faQX1y6e/3565-design-could-not-sponsor-visa-reason-for-rejection-for-international-candidates

Add 'could not sponsor visa' reason for rejection

---

app/routes/users.js
app/views/account/permissions.njk
app/views/onboard/relationship.njk
app/views/organisation-settings/organisational-permissions/edit.njk
app/views/organisation-settings/users/edit-permissions/additional-permissions.njk
app/views/organisation-settings/users/edit-permissions/check.njk
app/views/organisation-settings/users/new/additional-permissions.njk
app/views/organisation-settings/users/new/check.njk
app/views/organisation-settings/users/show.njk

- remove user permission level branching question
- remove every one can view guidance bullets on relationship pages
- playing back permissions - present each permission as separate row

Permissions changes

---

lib/middleware/authentication/authentication.js
server.js

Add 'staging' environment check

Fix authentication

---

app/data/generators/degree.js
app/data/generators/gcse.js
app/data/generators/interviews.js
app/data/generators/notes.js
app/data/generators/offer.js
app/data/generators/organisation.js
app/data/generators/personal-details.js
app/data/generators/references.js
app/data/generators/school-experience.js
app/data/generators/submittedDate.js
app/data/generators/user.js
app/data/generators/work-history.js
package.json
scripts/generate-applications.js
scripts/generate-users.js

- Update faker package to `v5.5.3`
- Fix deprecation warnings
- `faker.random.boolean` is now located in `faker.datatype.boolean`
- `faker.random.number` is now located in `faker.datatype.number`
- `faker.random.uuid` is now located in `faker.datatype.uuid`

Update faker package

---

app/data/helpers/application.js
app/routes.js
app/routes/applications.js
app/routes/assign.js
app/routes/interviews.js
app/routes/notes.js
app/routes/offer.js
app/routes/users.js
app/views/_includes/applications/assigned-users.njk
app/views/_includes/applications/assignees.njk
app/views/_includes/applications/h1.njk
app/views/applications/assign/index.njk

See [Application assignment: Allow users to assign an application to another user in their organisation](https://trello.com/c/9KwF7VPs)
- Show assigned users for a given application
- Allow users to change (add/update/remove) assigned users

Assign an application to one or more users

---

app/data/generators/assigned-users.js
app/filters.js
app/routes/application-list.js
app/views/_includes/application-card.njk
app/views/_includes/filter-panel.njk
app/views/index.njk
scripts/generate-applications.js

See [Application assignment: Allow users to filter applications they see by assigned users](https://trello.com/c/EkW2x0uf)
- Generate assigned users data
- Show assigned users on each application card
- Add assigned users filter to filter panel using the checkbox filter component
- Allow filtering by unassigned and assigned

Add application assignment filters

---

app/assets/sass/application.scss
app/routes/application-list.js
app/routes/assign.js
app/views/_components/checkbox-filter/template.njk
app/views/applications/notes/show.njk
app/views/applications/timeline/show.njk

Included in this update:
- Add notification banner to notes and timeline sections to show when a flash message is available
- Update Checkbox Filter to include hint text if provided
- Add hint to assigned user checkboxes if the name is a duplicate
- Updated user assignment form to only include a hint if the name is a duplicate
- Updating sort orders to be first name, last name AND email address to support ordering duplicate names

Application assignment updates

---

app/data/generators/assigned-users.js

- Fix check to see if the user already exists
- Limit the number of assigned users to between 1 and 3

Update assigned user generator

---

app/routes/data.js
app/views/data/statistics/status/index.njk

Move the totals row to a `tfoot`

Update status report

---

app/routes/data.js
app/views/data/index.njk
app/views/data/statistics/attrition/index.njk
app/views/data/statistics/status/index.njk

- removed column sorting
- removed link to the individual course page
- added download link to the CSV
- added download data generator
- updated content (column headings)
- Updated the report landing page to separate export data from provider reports

Update candidate drop out report

---

app/data/generators/events.js
app/data/generators/offer.js
app/data/generators/submittedDate.js
app/data/session-data-defaults.js
app/data/statistics/status.json
app/data/statistics/status/bishop-grosseteste-university.json
app/data/statistics/status/chiltern-training.json
app/data/statistics/status/glf-scitt.json
app/data/statistics/status/goldsmiths-university-of-london.json
app/data/statistics/status/ignite-teaching-school.json
app/data/statistics/status/the-oaks-norfolk.json
app/data/statistics/status/the-university-of-sheffield.json
app/data/statistics/status/university-cambridge.json
app/filters.js
app/routes/application-list.js
app/routes/data.js
app/routes/edit-condition-statuses.js
app/routes/reconfirm-offer.js
app/routes/settings.js
app/routes/users.js
app/views/_includes/applications/diversity-information.njk
app/views/_includes/filter-panel.njk
app/views/_includes/reasons/conditions.njk
app/views/applications/offer/show.njk
app/views/data/export/index.njk
app/views/organisation-settings/users/delete.njk
scripts/applications/constants.js
scripts/generate-applications.js

Change: 
- `awaiting conditions` to `conditions pending`
- `ready to enroll` to `recruited`
See [trello card](https://trello.com/c/NelkPFJA)

Update awaiting conditions and ready to enroll statuses

---

app/views/data/index.njk
app/views/data/statistics/attrition/index.njk

Update candidate drop out rate report

---

app/data/generators/personal-details.js
app/data/helpers/statistics.js
app/views/_includes/applications/diversity-information.njk
scripts/applications/constants.js
scripts/generate-applications.js

Update the personal details generator. 
Add weightings for:
- sex
- disability
- ethnicity group and background
Uses _real_ weightings from existing Apply data.

Add weightings to diversity data

---

app/data/statistics/attrition/wren-academy.json
app/routes/data.js
app/views/data/index.njk
app/views/data/statistics/attrition/index.njk

Replace:
- Applications withdrawn before offer made
- Offers declined and applications withdrawn after offer made
With: 
- Before offer made (applications withdrawn)
- While offer being considered (offers declined and applications withdrawn)
- After offer accepted (applications withdrawn)

Update drop out report headings and data

---

app/routes/data.js

Changes:
- rename files
- `sex-disability-ethicity-and-age-of-candidates-cyle-provider-name-datetime.zip`
- `candidate-age-cycle-provider-name-datetime.csv`
- `candidate-disability-cycle-provider-name-datetime.csv`
- `candidate-ethnicity-cycle-provider-name-datetime.csv`
- `candidate-sex-cycle-provider-name-datetime.csv`
- delete unnecessary files after download
- comment out unnecessary code (to be removed later)

Update diversity report exports

---

app/data/locations.json
app/data/subjects.json
app/routes/application-list.js
app/views/_includes/filter-panel.njk

Update the application list filters to dynamically generate the training locations and subjects based on the locations and subjects in the application data.

Update filters to use default subjects and locations

---

app/data/generators/course.js

Use course locations derived from the static JSON file.
The JSON file is used in the application list to generate options for the training location filter.

Update course locations

---

app/data/generators/gcse.js
app/views/_examples/qualifications/degree.njk
app/views/_examples/qualifications/english.njk
app/views/_examples/qualifications/gcse.njk
app/views/_includes/applications/degrees.njk
app/views/_includes/applications/english-language-qualification.njk
app/views/_includes/applications/gcses.njk
app/views/_includes/applications/other-qualifications.njk
scripts/generate-applications.js

If a GCSE qualification is lower than grade C, candidates are asked two follow-up questions:
- "Are you currently studying to retake your GCSE in [English|maths|science]?" (Yes/no)
- If they answered no, "If you have other evidence of having maths skills at the required standard, give details (optional)"
If they're going to retake:
If they're not going to retake:

Add GCSE retake answers to the qualifications section

---

app/routes/reports.js
app/views/_includes/reports/diversity/disability.njk
app/views/reports/diversity/index.njk
app/views/reports/diversity/show.njk
app/views/reports/hesa/index.njk
app/views/reports/index.njk

See Trello: https://trello.com/c/weBFdFeO/4456-consider-hiding-the-diversity-report-while-users-could-be-identified

Hide diversity report if too few candidates

---

app/views/_includes/primary-navigation.njk

This is to match the design on production.

Move 'Reports' navigation item to the right

---

app/views/applications/index.njk

Remove 'sort by' feature

---

app/data/helpers/cycles.js
app/views/_components/application-card/_application-card.scss
app/views/_includes/application-card.njk

This reverts the design of the application list view to match production.

Revert application list view to match production

---

app/views/_components/offer-panel/template.njk
app/views/applications/offer/new/ske-length.njk

We've decided not to ask the question about when the course should be completed by, as:
* it doesn't really vary by provider
* the question is too definite - providers told us they give some flexibility to allow candidates to overlap with their ITT course if the candidate faces difficulty with completing it on time
* candidates won’t get paid the SKE bursary if their SKE course overlaps with their ITT course

Drop SKE deadline question

---

package-lock.json
package.json

Remove keypather npm module

---

app/routes/assign.js
app/routes/confirm-deferred-offer.js
app/routes/defer-offer.js
app/routes/edit-condition-statuses.js
app/routes/edit-course.js
app/routes/edit-offer.js
app/routes/interviews.js
app/routes/make-offer.js
app/routes/notes.js
app/routes/notification-settings.js
app/routes/organisational-permissions.js
app/routes/reject-application.js
app/routes/users.js
app/routes/withdraw-application.js
app/routes/withdraw-offer.js
app/views/account/notifications/index.njk
app/views/account/notifications/online.njk
app/views/applications/feedback/show.njk
app/views/applications/interviews/index.njk
app/views/applications/notes/index.njk
app/views/applications/notes/show.njk
app/views/applications/offer/show.njk
app/views/applications/references/index.njk
app/views/applications/timeline/show.njk
app/views/organisation-settings/organisational-permissions/index.njk
app/views/organisation-settings/users/index.njk
app/views/organisation-settings/users/show.njk
package-lock.json
package.json

These notifications messages relied on a npm module, and no longer work since upgrading to the latest version of the prototype kit.
I'm just removing all the notifications messages for now, as they're not super important. If needed they can be re-implemented later.

Remove flash messages

---

app/views/_includes/application-card.njk
app/views/_includes/applications/contact-details.njk
app/views/applications/notes/index.njk
app/views/applications/references/index.njk
app/views/applications/show.njk
app/views/applications/timeline/show.njk

This PR shows what a provider will see if a candidate updates parts of their application after they've applied.
Trello ticket:
https://trello.com/c/oO097S3x/84-iterate-the-manage-prototype-to-reflect-changed-applications

Showing providers that an application has been updated

---

app/assets/javascripts/application.js
app/assets/javascripts/jquery-1.11.3.js
app/assets/sass/application.scss
app/assets/sass/core/_status.scss
app/assets/sass/core/_tag.scss
app/views/_components/application-card/_application-card.scss
app/views/_includes/application-card.njk
app/views/_includes/head.njk
app/views/_includes/scripts.njk
app/views/applications/index.njk
app/views/applications/interviews/new/index.njk
app/views/applications/notes/index.njk
app/views/applications/offer/confirm-deferred-offer/conditions.njk
app/views/applications/offer/confirm-deferred-offer/location.njk
app/views/applications/offer/edit/conditions.njk
app/views/applications/offer/new/conditions.njk
app/views/applications/offer/new/ske-length.njk
app/views/applications/offer/new/ske-reason.njk
app/views/applications/offer/new/ske.njk
package-lock.json
package.json

Update to v5.0.0

---

app/views/applications/reject/reasons.njk

Adding new rejection reasons. Details in https://trello.com/c/8QTE1MrV/2252-draft-content-for-new-and-updated-withdrawal-and-rejection-reasons?filter=member:petewilliams89

Updating rejection reasons

---

app/routes/withdraw-application.js
app/routes/withdraw-offer.js
app/views/_email.njk
app/views/_includes/reasons/personal-statement.njk
app/views/_includes/reasons/qualifications.njk
app/views/applications/offer/withdraw/check.njk
app/views/applications/offer/withdraw/index.njk
app/views/email/candidate-withdraw-confirm.njk
app/views/email/candidate-withdraw-reject.njk
scripts/applications/constants.js

Withdraw events in timeline
Adding emails

Withdrawal updates

---

app/routes/withdraw-application.js
app/views/applications/offer/show.njk
app/views/applications/show.njk
app/views/applications/withdraw/index.njk
app/views/applications/withdraw/request.njk
app/views/email/candidate-withdraw-confirm.njk
app/views/email/candidate-withdraw-reject.njk

Updates between testing sessions.
Moving/renaming the links into the journeys.

Withdrawal iteration

---

app/routes/withdraw-application.js
app/views/applications/show.njk
app/views/applications/withdraw/check.njk
app/views/applications/withdraw/index.njk

Withdrawal request updates
